<?php

/**
 * @file
 * Contains custom_token.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function custom_token_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the custom_token module.
    case 'help.page.custom_token':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Create Custom Tokens') . '</p>';
      return $output;

    default:
  }
}
